apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service
spec:
  type: ClusterIP
  selector:
    app: myapp-service
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
